# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

# reference: https://github.com/mlflow/mlflow/blob/master/.pre-commit-config.yaml
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.2.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  - id: check-added-large-files

- repo: local
  hooks:
    - id: ruff
      name: ruff
      entry: ruff
      language: system
      types: [python]
      stages: [commit]

- repo: local
  hooks:
    - id: black
      name: black
      entry: black
      language: system
      types: [python]
      stages: [commit]

# from: https://python-poetry.org/docs/master/pre-commit-hooks/#usage
- repo: https://github.com/python-poetry/poetry
  rev: '1.4.2'
  hooks:
    - id: poetry-check
    # - id: poetry-lock => we omit this because we want our dependencies to be "locked" when developed
    - id: poetry-export
      args: ["--without-hashes", "--with", "test", "-o", "requirements.txt"]
