# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

# reference: https://github.com/mlflow/mlflow/blob/master/.pre-commit-config.yaml
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.2.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  - id: check-added-large-files

- repo: local
  hooks:
    - id: ruff
      name: ruff
      entry: ruff
      language: system
      types: [python]
      stages: [commit]

- repo: local
  hooks:
    - id: ruff-format
      name: ruff-format
      entry: ruff format .
      language: system
      types: [python]
      stages: [commit]

# https://pdm-project.org/latest/usage/advanced/#hooks-for-pre-commit
- repo: https://github.com/pdm-project/pdm
  rev: 2.12.3
  hooks:
    # - id: pdm-lock-check => we omit this because we want our dependencies to be "locked" when developed
    - id: pdm-export
      name: export-test-dependencies
      args: ["--without-hashes", "-f", "requirements", "-o", "requirements.test.txt", "-G", "test"]
      files: ^pdm.lock$

    - id: pdm-export
      name: export-production-dependencies
      args: ["--without-hashes", "-f", "requirements", "-o", "requirements.production.txt", "--production"]
      files: ^pdm.lock$
