[tool.poetry]
name = "techlog"
version = "0.1.0"
description = "a microservice for CRUD operations for the Techlog project"
authors = ["UponTheSky <sailing.to.orbis@gmail.com>"]
license = "Proprietary"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
fastapi = "^0.95.0"
sqlalchemy = "^2.0.4"
pymysql = "^1.0.2"
alembic = "^1.9.4"
python-multipart = "^0.0.6"
uvicorn = "^0.21.1"
python-jose = {extras = ["cryptography"], version = "^3.3.0"}
passlib = {extras = ["bcrypt"], version = "^1.7.4"}

[tool.poetry.group.dev.dependencies]
black = "^23.1.0"
pytest = "^7.2.2"
ruff = "^0.0.254"

[tool.ruff]

[tool.black]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
