# reference: https://docs.github.com/en/actions/creating-actions/creating-a-composite-action
name: dependencies
description: prepare for required python dependencies

inputs:
  python-version:
    description: Python version
    required: false
    default: '3.11'
  dependency-file:
    description: The name of the file that is required for installing dependencies
    required: true

runs:
  using: composite
  steps:
    - name: setup the python environment
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python-version }}
    - name: install dependencies
      env:
        DEPENDENCY_FILE: ${{ inputs.dependency-file }}
      run: |
        python -m pip install --upgrade pip
        pip install --no-cache-dir -r $DEPENDENCY_FILE
      shell: bash
