name: 'Pull Request check'

on:
  push:
    paths-ignore:
      - alembic.ini
      - 'db_migration/**'
      - README.md
      - 'docs/**'

# reference: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python
jobs:
  build:
    name: build the project
    runs-on: ubuntu-latest
    steps:
      - name: checkout the repo
        uses: actions/checkout@v3
      - name: setup the python environment
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --no-cache-dir -r requirements.txt
